# Standard library module used to read environment variables
import os

# Loads variables stored in a local .env file into the process environment
from dotenv import load_dotenv

# Official OpenAI Python client
from openai import OpenAI


# ---------------------------------------------------------
# 1. LOAD CONFIGURATION
# ---------------------------------------------------------

# Read the .env file located in the project environment
# Example:
# OPENAI_API_KEY=...
# OPENAI_MODEL=...
load_dotenv()


# Retrieve the values from the environment.
# os.getenv(...) returns the value associated with the variable name.
api_key = os.getenv("OPENAI_API_KEY")
model = os.getenv("OPENAI_MODEL")


# Defensive validation:
# we stop the program immediately if the API key is missing.
if not api_key:
    raise ValueError(
        "OPENAI_API_KEY is missing from the .env file."
    )


# Same validation for the model name.
if not model:
    raise ValueError(
        "OPENAI_MODEL is missing from the .env file."
    )


# ---------------------------------------------------------
# 2. CREATE THE OPENAI CLIENT
# ---------------------------------------------------------

# Create an OpenAI client object authenticated with our API key.
# At this moment, we are only preparing the client.
# No question has been sent to the model yet.
client = OpenAI(api_key=api_key)


# ---------------------------------------------------------
# 3. DEFINE A REUSABLE FUNCTION
# ---------------------------------------------------------

def ask_llm(question: str) -> str:
    """
    Send a question to the LLM and return only the generated text.

    Parameters
    ----------
    question : str
        The user's question.

    Returns
    -------
    str
        The text generated by the model.
    """

    # This is the actual API call.
    #
    # We send:
    # - the model we want to use
    # - the input text
    #
    # The response variable receives the complete object
    # returned by the OpenAI API.
    response = client.responses.create(
        model=model,
        input=question,
    )

    # The API response contains multiple pieces of information.
    # output_text extracts only the final text generated by the model.
    return response.output_text


# ---------------------------------------------------------
# 4. RUN A SIMPLE TEST
# ---------------------------------------------------------

# This condition is true only when this file is executed directly:
#
# python app/core/llm.py
#
# It is NOT executed when llm.py is imported from another Python file.
if __name__ == "__main__":

    # Test question used for our first LLM connection
    question = (
        "What is engineering risk? "
        "Answer in two sentences."
    )

    # Display the question in the terminal
    print("Question:")
    print(question)

    # Call our function.
    # The function sends the question to the model
    # and returns the generated answer.
    answer = ask_llm(question)

    # Display the response
    print("\nLLM response:")
    print(answer)